# -*- coding: utf-8 -*-
"""resultadopm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16OnQZv6LRFmni6PXcz9Ejtdr7CfeMOgJ
"""

pip install pdfplumber pandas openpyxl

import pdfplumber
import pandas as pd
import re

PDF_PROVA = "arquivo_prova.pdf"
PDF_PSICO = "dbb35138-a62c-45e9-9b89-890b96258841.pdf"
PDF_COTAS = "cotas.pdf"

print("Processando dados gerais dos candidatos...")


def carregar_psicotecnico():
    aptos = set()
    with pdfplumber.open(PDF_PSICO) as pdf:
        for page in pdf.pages:
            text = page.extract_text()
            if not text:
                continue
            for line in text.split("\n"):
                parts = line.split()
                if len(parts) >= 3 and parts[-1] == "APTO":
                    aptos.add(parts[0])
    return aptos



def carregar_prova():
    candidatos = []

    padrao = re.compile(
        r"(25\d{8})\s+(.+?)\s+\d+,\d+\s+\d+,\d+\s+(\d+,\d+)\s+(SIM|---)\s+(\d+º)\s+(APROVADO|ELIMINADO)",
        re.UNICODE
    )

    with pdfplumber.open(PDF_PROVA) as pdf:
        for page in pdf.pages:
            text = page.extract_text()
            if not text:
                continue

            for m in padrao.finditer(text):
                candidatos.append({
                    "inscricao": m.group(1),
                    "nome": m.group(2).strip(),
                    "nota_total": float(m.group(3).replace(",", ".")),
                    "classificacao_prova": int(m.group(5).replace("º", "")),
                    "situacao_prova": m.group(6)
                })

    return pd.DataFrame(candidatos)



def carregar_cotas():
    registros = []
    padrao = re.compile(r"(25\d{8}).+?(APROVADO|ELIMINADO|AMPLA|\(AMPLA\)|AFRO|PCD|INDIGENA)", re.IGNORECASE)

    with pdfplumber.open(PDF_COTAS) as pdf:
        for page in pdf.pages:
            text = page.extract_text()
            if not text:
                continue
            for line in text.split("\n"):
                m = padrao.search(line)
                if m:
                    registros.append({
                        "inscricao": m.group(1),
                        "cota": "COTA"  # se aparecer aqui, tem cota
                    })

    return pd.DataFrame(registros)



psico_aptos = carregar_psicotecnico()
df = carregar_prova()
cotas = carregar_cotas()

# Psicológico
df["psicotecnico"] = df["inscricao"].apply(
    lambda x: "APTO" if x in psico_aptos else "NÃO APTO"
)

# Cotas
df = df.merge(cotas, on="inscricao", how="left")
df["cota"] = df["cota"].fillna("SEM COTA")


df["status_final"] = df.apply(
    lambda x: "PASSOU EM TUDO" if x["situacao_prova"] == "APROVADO" and x["psicotecnico"] == "APTO"
    else "NÃO PASSOU",
    axis=1
)


aprovados = df[df["status_final"] == "PASSOU EM TUDO"].copy()
aprovados = aprovados.sort_values(by="nota_total", ascending=False).reset_index(drop=True)
aprovados["rank_passou"] = aprovados.index + 1



reprovados = df[df["status_final"] == "NÃO PASSOU"].copy()
reprovados = reprovados.sort_values(by="nota_total", ascending=False).reset_index(drop=True)
reprovados["rank_nao_passou"] = reprovados.index + 1


with pd.ExcelWriter("resultado_geral_candidatos.xlsx", engine="openpyxl") as writer:
    df.to_excel(writer, sheet_name="Resultado Geral", index=False)
    aprovados.to_excel(writer, sheet_name="Passaram em tudo", index=False)
    reprovados.to_excel(writer, sheet_name="Nao passaram", index=False)

print("\nPronto!")
print("Gerado: resultado_geral_candidatos.xlsx")
print("Inclui:")
print("- Resultado geral")
print("- Ranking de quem passou em tudo")
print("- Ranking de quem não passou")

from google.colab import files

files.upload()

pip install pdfplumber pandas openpyxl reportlab

import pdfplumber
import pandas as pd
import re
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas

PDF_PROVA = "arquivo_prova.pdf"
PDF_PSICO = "dbb35138-a62c-45e9-9b89-890b96258841.pdf"
PDF_COTAS = "cotas.pdf"


BUSCA = "João Lucas da Silva"
# BUSCA = "2503015858"
# BUSCA = "JOAO"

print("Processando região MARINGÁ...")


def carregar_psicotecnico():
    aptos = set()
    with pdfplumber.open(PDF_PSICO) as pdf:
        for page in pdf.pages:
            text = page.extract_text()
            if not text:
                continue
            for line in text.split("\n"):
                parts = line.split()
                if len(parts) >= 3 and parts[-1] == "APTO":
                    aptos.add(parts[0])
    return aptos



def carregar_prova_maringa():
    candidatos = []

    padrao = re.compile(
        r"(25\d{8})\s+(.+?)\s+\d+,\d+\s+\d+,\d+\s+(\d+,\d+)\s+(SIM|---)\s+(\d+º)\s+(APROVADO|ELIMINADO)",
        re.UNICODE
    )

    with pdfplumber.open(PDF_PROVA) as pdf:
        capturar = False

        for page in pdf.pages:
            text = page.extract_text()
            if not text:
                continue

            if "3ª REGIÃO/MARINGÁ" in text:
                capturar = True

            if capturar:
                for m in padrao.finditer(text):
                    candidatos.append({
                        "inscricao": m.group(1),
                        "nome": m.group(2).strip(),
                        "nota_total": float(m.group(3).replace(",", ".")),
                        "classificacao_prova": int(m.group(5).replace("º", "")),
                        "situacao_prova": m.group(6)
                    })

            if "4ª REGIÃO" in text:
                break

    return pd.DataFrame(candidatos)



def carregar_cotas():
    registros = []
    padrao = re.compile(r"(25\d{8}).+?(AMPLA|PCD|NEGRO|INDIGENA|COTA.+)", re.IGNORECASE)

    with pdfplumber.open(PDF_COTAS) as pdf:
        for page in pdf.pages:
            text = page.extract_text()
            if not text:
                continue
            for line in text.split("\n"):
                m = padrao.search(line)
                if m:
                    registros.append({
                        "inscricao": m.group(1),
                        "cota": m.group(2).upper()
                    })

    return pd.DataFrame(registros)




def gerar_pdf_individual(c):
    filename = f"resultado_{c['inscricao']}.pdf"
    pdf = canvas.Canvas(filename, pagesize=A4)

    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawString(50, 800, "Resultado Individual do Candidato")

    pdf.setFont("Helvetica", 12)
    y = 760
    pdf.drawString(50, y, f"Inscrição: {c['inscricao']}"); y -= 20
    pdf.drawString(50, y, f"Nome: {c['nome']}"); y -= 20
    pdf.drawString(50, y, f"Nota: {c['nota_total']}"); y -= 20
    pdf.drawString(50, y, f"Situação na Prova: {c['situacao_prova']}"); y -= 20
    pdf.drawString(50, y, f"Psicotécnico: {c['psicotecnico']}"); y -= 20

    if c["cota"] != "SEM COTA":
        pdf.drawString(50, y, f"Cota: {c['cota']}"); y -= 20

    if "rank_final" in c:
        pdf.drawString(50, y, f"Ranking Final: {c['rank_final']}"); y -= 20

    pdf.save()



psico = carregar_psicotecnico()
df = carregar_prova_maringa()
cotas = carregar_cotas()

df["psicotecnico"] = df["inscricao"].apply(
    lambda x: "APTO" if x in psico else "NÃO APTO"
)

df = df.merge(cotas, on="inscricao", how="left")
df["cota"] = df["cota"].fillna("SEM COTA")

# Status final
df["status_final"] = df.apply(
    lambda x: "PASSOU EM TUDO"
    if x["situacao_prova"] == "APROVADO" and x["psicotecnico"] == "APTO"
    else "NÃO PASSOU",
    axis=1
)

# PASSARAM
aprovados = df[df["status_final"] == "PASSOU EM TUDO"].copy()
aprovados = aprovados.sort_values(by="nota_total", ascending=False).reset_index(drop=True)
aprovados["rank_final"] = aprovados.index + 1

# NÃO PASSARAM
reprovados = df[df["status_final"] == "NÃO PASSOU"].copy()

with pd.ExcelWriter("resultado_maringa_final.xlsx", engine="openpyxl") as writer:
    df.to_excel(writer, sheet_name="Resultado Geral Maringa", index=False)
    aprovados.to_excel(writer, sheet_name="Passaram Tudo", index=False)
    reprovados.to_excel(writer, sheet_name="Nao Passaram", index=False)

print("\nExcel gerado: resultado_maringa_final.xlsx")


for _, c in aprovados.iterrows():
    gerar_pdf_individual(c)

print("PDFs individuais gerados para aprovados finais.")


if BUSCA:
    def localizar(df, busca):
        if busca.isdigit():
            return df[df["inscricao"] == busca]
        return df[df["nome"].str.contains(busca, case=False, regex=False)]

    pessoa = localizar(df, BUSCA)

    if pessoa.empty:
        print("\nCandidato não encontrado em Maringá.")
    else:
        p = pessoa.iloc[0]
        print("\n===== RESULTADO DO CANDIDATO =====")
        print(p)
        gerar_pdf_individual(p)
        print(f"\nPDF individual gerado: resultado_{p['inscricao']}.pdf")

pip install pdfplumber pandas reportlab

import pdfplumber
import pandas as pd
import re
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas

PDF_PROVA = "arquivo_prova.pdf"
PDF_PSICO = "dbb35138-a62c-45e9-9b89-890b96258841.pdf"
PDF_COTAS = "cotas.pdf"


BUSCA = "João Lucas da Silva"

def carregar_psicotecnico():
    aptos = set()
    with pdfplumber.open(PDF_PSICO) as pdf:
        for page in pdf.pages:
            text = page.extract_text()
            if not text:
                continue
            for line in text.split("\n"):
                parts = line.split()
                if len(parts) >= 3 and parts[-1] == "APTO":
                    aptos.add(parts[0])
    return aptos


def carregar_prova():
    candidatos = []
    padrao = re.compile(
        r"(25\d{8})\s+(.+?)\s+\d+,\d+\s+\d+,\d+\s+(\d+,\d+)\s+(SIM|---)\s+(\d+º)\s+(APROVADO|ELIMINADO)",
        re.UNICODE
    )

    with pdfplumber.open(PDF_PROVA) as pdf:
        for page in pdf.pages:
            text = page.extract_text()
            if not text:
                continue
            for m in padrao.finditer(text):
                candidatos.append({
                    "inscricao": m.group(1),
                    "nome": m.group(2).strip(),
                    "nota_total": float(m.group(3).replace(",", ".")),
                    "situacao_prova": m.group(6)
                })
    return pd.DataFrame(candidatos)


def carregar_cotas():
    registros = []
    padrao = re.compile(r"(25\d{8}).+?(AMPLA|PCD|NEGRO|INDIGENA|COTA.+)", re.IGNORECASE)

    with pdfplumber.open(PDF_COTAS) as pdf:
        for page in pdf.pages:
            text = page.extract_text()
            if not text:
                continue
            for line in text.split("\n"):
                m = padrao.search(line)
                if m:
                    registros.append({
                        "inscricao": m.group(1),
                        "cota": m.group(2).upper()
                    })
    return pd.DataFrame(registros)


def gerar_pdf_individual(c):
    arquivo = f"resultado_individual_{c['inscricao']}.pdf"
    pdf = canvas.Canvas(arquivo, pagesize=A4)

    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawString(50, 800, "Resultado Individual do Candidato")

    pdf.setFont("Helvetica", 12)
    y = 760
    pdf.drawString(50, y, f"Inscrição: {c['inscricao']}"); y -= 20
    pdf.drawString(50, y, f"Nome: {c['nome']}"); y -= 20
    pdf.drawString(50, y, f"Nota: {c['nota_total']}"); y -= 20
    pdf.drawString(50, y, f"Situação na Prova: {c['situacao_prova']}"); y -= 20
    pdf.drawString(50, y, f"Psicotécnico: {c['psicotecnico']}"); y -= 20

    if c["cota"] != "SEM COTA":
        pdf.drawString(50, y, f"Cota: {c['cota']}"); y -= 20

    pdf.drawString(50, y, f"Status Final: {c['status_final']}")

    pdf.save()
    print(f"\nPDF gerado: {arquivo}")



print("Processando candidato...")

psico = carregar_psicotecnico()
prova = carregar_prova()
cotas = carregar_cotas()

df = prova.copy()
df["psicotecnico"] = df["inscricao"].apply(lambda x: "APTO" if x in psico else "NÃO APTO")
df = df.merge(cotas, on="inscricao", how="left")
df["cota"] = df["cota"].fillna("SEM COTA")

df["status_final"] = df.apply(
    lambda x: "PASSOU EM TUDO"
    if x["situacao_prova"] == "APROVADO" and x["psicotecnico"] == "APTO"
    else "NÃO PASSOU",
    axis=1
)

def localizar(df, busca):
    if busca.isdigit():
        return df[df["inscricao"] == busca]
    return df[df["nome"].str.contains(busca, case=False, regex=False)]

pessoa = localizar(df, BUSCA)

if pessoa.empty:
    print("\nCandidato não encontrado nos PDFs.")
else:
    p = pessoa.iloc[0]

    print("\n===== RESULTADO DO CANDIDATO =====")
    print("Inscrição:", p["inscricao"])
    print("Nome:", p["nome"])
    print("Nota:", p["nota_total"])
    print("Situação Prova:", p["situacao_prova"])
    print("Psicotécnico:", p["psicotecnico"])
    print("Cota:", p["cota"])
    print("Status Final:", p["status_final"])

    gerar_pdf_individual(p)

pip install pdfplumber pandas

import pdfplumber
import pandas as pd
import re
import unicodedata

PDF_PROVA = "arquivo_prova.pdf"
PDF_PSICO = "dbb35138-a62c-45e9-9b89-890b96258841.pdf"
PDF_COTAS = "cotas.pdf"

BUSCA = "JOAO LUCAS DA SILVA"


def normalize(s):
    if not isinstance(s, str):
        return s
    return ''.join(c for c in unicodedata.normalize('NFD', s)
                   if unicodedata.category(c) != 'Mn').upper().strip()


norm_busca = normalize(BUSCA)

print("Processando...")


psico_aptos = set()
with pdfplumber.open(PDF_PSICO) as pdf:
    for page in pdf.pages:
        text = page.extract_text()
        if not text:
            continue
        for line in text.split("\n"):
            parts = line.split()
            if len(parts) >= 3 and parts[-1] == "APTO":
                psico_aptos.add(parts[0])



candidatos = []
padrao = re.compile(
    r"(25\d{8})\s+(.+?)\s+\d+,\d+\s+\d+,\d+\s+(\d+,\d+)\s+(SIM|---)\s+(\d+º)\s+(APROVADO|ELIMINADO)"
)

with pdfplumber.open(PDF_PROVA) as pdf:
    for page in pdf.pages:
        text = page.extract_text()
        if not text:
            continue

        for m in padrao.finditer(text):
            candidatos.append({
                "inscricao": m.group(1),
                "nome": m.group(2).strip(),
                "nota_total": float(m.group(3).replace(",", ".")),
                "situacao_prova": m.group(6)
            })

df = pd.DataFrame(candidatos)


if df.empty:
    print("Nenhum candidato foi extraído da prova. Possível layout diferente.")
    quit()



cotas = []
with pdfplumber.open(PDF_COTAS) as pdf:
    for page in pdf.pages:
        text = page.extract_text()
        if not text:
            continue

        for line in text.split("\n"):
            if "25" in line:
                parts = line.split()
                for p in parts:
                    if p.startswith("25") and len(p) >= 10:
                        cotas.append({"inscricao": p, "cota": "COTA"})

cotas = pd.DataFrame(cotas).drop_duplicates("inscricao")

df = df.merge(cotas, on="inscricao", how="left")
df["cota"] = df["cota"].fillna("SEM COTA")

df["psicotecnico"] = df["inscricao"].apply(lambda x: "APTO" if x in psico_aptos else "NÃO APTO")

df["status_final"] = df.apply(
    lambda x: "PASSOU EM TUDO"
    if x["situacao_prova"] == "APROVADO" and x["psicotecnico"] == "APTO"
    else "NÃO PASSOU",
    axis=1
)



df["nome_normalizado"] = df["nome"].apply(normalize)

result = df[
    df["nome_normalizado"].str.contains(norm_busca, case=False, regex=False)
]

if result.empty:
    print("\n⚠️ O candidato NÃO aparece no PDF da PROVA.")
    print("Motivos mais comuns:")
    print("- Está em outra região")
    print("- Nome grafado diferente")
    print("- Não está entre classificados publicados")
    quit()

p = result.iloc[0]

print("\n===== RESULTADO DO CANDIDATO =====")
print("Inscrição:", p["inscricao"])
print("Nome:", p["nome"])
print("Nota:", p["nota_total"])
print("Situação Prova:", p["situacao_prova"])
print("Psicotécnico:", p["psicotecnico"])
print("Cota:", p["cota"])
print("Status Final:", p["status_final"])

pip install pdfplumber pandas openpyxl reportlab

import pdfplumber
import pandas as pd
import re
import unicodedata
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas

PDF_PROVA = "arquivo_prova.pdf"
PDF_PSICO = "dbb35138-a62c-45e9-9b89-890b96258841.pdf"
PDF_COTAS = "cotas.pdf"


BUSCA = "2503008621"

def normalize(s):
    if not isinstance(s, str):
        return s
    return ''.join(c for c in unicodedata.normalize('NFD', s)
                   if unicodedata.category(c) != 'Mn').upper().strip()


norm_busca = normalize(BUSCA)


psico_aptos = set()
with pdfplumber.open(PDF_PSICO) as pdf:
    for page in pdf.pages:
        text = page.extract_text()
        if not text:
            continue
        for line in text.split("\n"):
            parts = line.split()
            if len(parts) >= 3 and parts[-1] == "APTO":
                psico_aptos.add(parts[0])



candidatos = []
padrao = re.compile(
    r"(25\d{8})\s+(.+?)\s+\d+,\d+\s+\d+,\d+\s+(\d+,\d+)\s+(SIM|---)\s+(\d+º)\s+(APROVADO|ELIMINADO)"
)

with pdfplumber.open(PDF_PROVA) as pdf:
    for page in pdf.pages:
        text = page.extract_text()
        if not text:
            continue
        for m in padrao.finditer(text):
            candidatos.append({
                "inscricao": m.group(1),
                "nome": m.group(2).strip(),
                "nota_total": float(m.group(3).replace(",", ".")),
                "situacao_prova": m.group(6)
            })

df = pd.DataFrame(candidatos)

if df.empty:
    print("Erro: não foi possível extrair dados da PROVA.")
    quit()


cotas = []
with pdfplumber.open(PDF_COTAS) as pdf:
    for page in pdf.pages:
        text = page.extract_text()
        if not text:
            continue
        for line in text.split("\n"):
            if "25" in line:
                parts = line.split()
                for p in parts:
                    if p.startswith("25") and len(p) >= 10:
                        cotas.append({"inscricao": p, "cota": "COTA"})

cotas = pd.DataFrame(cotas).drop_duplicates("inscricao")

df = df.merge(cotas, on="inscricao", how="left")
df["cota"] = df["cota"].fillna("SEM COTA")
df["psicotecnico"] = df["inscricao"].apply(lambda x: "APTO" if x in psico_aptos else "NÃO APTO")

df["status_final"] = df.apply(
    lambda x: "PASSOU EM TUDO"
    if x["situacao_prova"] == "APROVADO" and x["psicotecnico"] == "APTO"
    else "NÃO PASSOU",
    axis=1
)


df = df.sort_values(by="nota_total", ascending=False).reset_index(drop=True)
df["rank_geral"] = df.index + 1

aptos = df[df["status_final"] == "PASSOU EM TUDO"].copy()
aptos = aptos.sort_values(by="nota_total", ascending=False).reset_index(drop=True)
aptos["rank_aptos"] = aptos.index + 1

aptos["rank_cota"] = (
    aptos.groupby("cota")["nota_total"]
    .rank(method="dense", ascending=False)
    .astype(int)
)


df["nome_normalizado"] = df["nome"].apply(normalize)

if BUSCA.isdigit():
    pessoa = df[df["inscricao"] == BUSCA]
else:
    pessoa = df[df["nome_normalizado"].str.contains(norm_busca, case=False, regex=False)]

if pessoa.empty:
    print("\nCandidato NÃO encontrado nos PDFs.")
    quit()

p = pessoa.iloc[0]

# merge ranks se aprovado
if p["status_final"] == "PASSOU EM TUDO":
    info_rank = aptos[aptos["inscricao"] == p["inscricao"]]
    if not info_rank.empty:
        p_rank = info_rank.iloc[0]
        rank_aptos = int(p_rank["rank_aptos"])
        rank_cota = int(p_rank["rank_cota"]) if p_rank["cota"] != "SEM COTA" else None
    else:
        rank_aptos = None
        rank_cota = None
else:
    rank_aptos = None
    rank_cota = None

print("\n===== RESULTADO COMPLETO DO CANDIDATO =====")
print("Inscrição:", p["inscricao"])
print("Nome:", p["nome"])
print("Nota:", p["nota_total"])
print("Ranking Geral:", int(p["rank_geral"]))
print("Situação Prova:", p["situacao_prova"])
print("Psicotécnico:", p["psicotecnico"])
print("Status Final:", p["status_final"])
print("Cota:", p["cota"])

if rank_aptos:
    print("Ranking entre Aptos:", rank_aptos)

if rank_cota:
    print("Ranking na Cota:", rank_cota)


individual = {
    "inscricao": p["inscricao"],
    "nome": p["nome"],
    "nota_total": p["nota_total"],
    "ranking_geral": int(p["rank_geral"]),
    "psicotecnico": p["psicotecnico"],
    "situacao_prova": p["situacao_prova"],
    "status_final": p["status_final"],
    "cota": p["cota"],
    "ranking_aptos": rank_aptos if rank_aptos else "",
    "ranking_cota": rank_cota if rank_cota else ""
}

df_ind = pd.DataFrame([individual])
df_ind.to_excel(f"resultado_individual_{p['inscricao']}.xlsx", index=False)
print(f"\nExcel gerado: resultado_individual_{p['inscricao']}.xlsx")


arquivo_pdf = f"resultado_individual_{p['inscricao']}.pdf"
pdf = canvas.Canvas(arquivo_pdf, pagesize=A4)

pdf.setFont("Helvetica-Bold", 16)
pdf.drawString(50, 800, "Resultado Individual do Candidato")

pdf.setFont("Helvetica", 12)
y = 760
pdf.drawString(50, y, f"Inscrição: {p['inscricao']}"); y -= 20
pdf.drawString(50, y, f"Nome: {p['nome']}"); y -= 20
pdf.drawString(50, y, f"Nota: {p['nota_total']}"); y -= 20
pdf.drawString(50, y, f"Ranking Geral: {int(p['rank_geral'])}"); y -= 20
pdf.drawString(50, y, f"Situação na Prova: {p['situacao_prova']}"); y -= 20
pdf.drawString(50, y, f"Psicotécnico: {p['psicotecnico']}"); y -= 20
pdf.drawString(50, y, f"Status Final: {p['status_final']}"); y -= 20

if p["cota"] != "SEM COTA":
    pdf.drawString(50, y, f"Cota: {p['cota']}"); y -= 20

if rank_aptos:
    pdf.drawString(50, y, f"Ranking entre Aptos: {rank_aptos}"); y -= 20

if rank_cota:
    pdf.drawString(50, y, f"Ranking na Cota: {rank_cota}")

pdf.save()
print(f"PDF gerado: {arquivo_pdf}")

import pdfplumber
import pandas as pd
import re

PDF_PROVA = "arquivo_prova.pdf"
PDF_PSICO = "dbb35138-a62c-45e9-9b89-890b96258841.pdf"
PDF_COTAS = "cotas.pdf"

print("Gerando lista de aprovados de MARINGÁ...")


def carregar_psicotecnico():
    aptos = set()
    with pdfplumber.open(PDF_PSICO) as pdf:
        for page in pdf.pages:
            text = page.extract_text()
            if not text:
                continue
            for line in text.split("\n"):
                parts = line.split()
                if len(parts) >= 3 and parts[-1] == "APTO":
                    aptos.add(parts[0])
    return aptos


def carregar_prova_maringa():
    candidatos = []
    padrao = re.compile(
        r"(25\d{8})\s+(.+?)\s+\d+,\d+\s+\d+,\d+\s+(\d+,\d+)\s+(SIM|---)\s+(\d+º)\s+(APROVADO|ELIMINADO)"
    )

    with pdfplumber.open(PDF_PROVA) as pdf:
        capturar = False
        for page in pdf.pages:
            text = page.extract_text()
            if not text:
                continue

            if "3ª REGIÃO/MARINGÁ" in text.upper():
                capturar = True

            if capturar:
                for m in padrao.finditer(text):
                    candidatos.append({
                        "inscricao": m.group(1),
                        "nome": m.group(2).strip(),
                        "nota_total": float(m.group(3).replace(",", ".")),
                        "situacao_prova": m.group(6)
                    })

            if "4ª REGIÃO" in text.upper():
                break

    return pd.DataFrame(candidatos)



def carregar_cotas():
    registros = []
    with pdfplumber.open(PDF_COTAS) as pdf:
        for page in pdf.pages:
            text = page.extract_text()
            if not text:
                continue
            for line in text.split("\n"):
                if "25" in line:
                    parts = line.split()
                    for p in parts:
                        if p.startswith("25") and len(p) >= 10:
                            registros.append({"inscricao": p, "cota": "COTA"})
    return pd.DataFrame(registros).drop_duplicates("inscricao")



psico = carregar_psicotecnico()
df = carregar_prova_maringa()
cotas = carregar_cotas()

if df.empty:
    print("Nenhum candidato encontrado em Maringá.")
    quit()

df["psicotecnico"] = df["inscricao"].apply(lambda x: "APTO" if x in psico else "NÃO APTO")
df = df.merge(cotas, on="inscricao", how="left")
df["cota"] = df["cota"].fillna("SEM COTA")

# STATUS FINAL
df["status_final"] = df.apply(
    lambda x: "PASSOU EM TUDO"
    if x["situacao_prova"] == "APROVADO" and x["psicotecnico"] == "APTO"
    else "NÃO PASSOU",
    axis=1
)


aprovados = df[df["status_final"] == "PASSOU EM TUDO"].copy()

# ORDENAR MELHOR → PIOR
aprovados = aprovados.sort_values(by="nota_total", ascending=False).reset_index(drop=True)
aprovados["ranking_maringa"] = aprovados.index + 1


aprovados.to_excel("aprovados_maringa_ordem_melhor_pior.xlsx", index=False)

print("\nPronto!")
print("Arquivo gerado: aprovados_maringa_ordem_melhor_pior.xlsx")
print(f"Total aprovados: {len(aprovados)}")

pip install pdfplumber pandas

import pdfplumber
import pandas as pd
import re
import unicodedata

PDF_PROVA = "arquivo_prova.pdf"
PDF_PSICO = "dbb35138-a62c-45e9-9b89-890b96258841.pdf"
PDF_COTAS = "cotas.pdf"


BUSCA = "2503008621"



def normalize(s):
    if not isinstance(s, str):
        return s
    return ''.join(c for c in unicodedata.normalize('NFD', s)
                   if unicodedata.category(c) != 'Mn').upper().strip()

norm_busca = normalize(BUSCA)


psico_aptos = set()
with pdfplumber.open(PDF_PSICO) as pdf:
    for page in pdf.pages:
        text = page.extract_text()
        if not text:
            continue
        for line in text.split("\n"):
            parts = line.split()
            if len(parts) >= 3 and parts[-1] == "APTO":
                psico_aptos.add(parts[0])


candidatos = []
padrao = re.compile(
    r"(25\d{8})\s+(.+?)\s+\d+,\d+\s+\d+,\d+\s+(\d+,\d+)\s+(SIM|---)\s+(\d+º)\s+(APROVADO|ELIMINADO)"
)

with pdfplumber.open(PDF_PROVA) as pdf:
    capturar = False
    for page in pdf.pages:
        text = page.extract_text()
        if not text:
            continue

        if "3ª REGIÃO/MARINGÁ" in text.upper():
            capturar = True

        if capturar:
            for m in padrao.finditer(text):
                candidatos.append({
                    "inscricao": m.group(1),
                    "nome": m.group(2).strip(),
                    "nota_total": float(m.group(3).replace(",", ".")),
                    "situacao_prova": m.group(6)
                })

        if "4ª REGIÃO" in text.upper():
            break

df = pd.DataFrame(candidatos)

if df.empty:
    print("Nenhum candidato encontrado em Maringá.")
    quit()


cotas = []
with pdfplumber.open(PDF_COTAS) as pdf:
    for page in pdf.pages:
        text = page.extract_text()
        if not text:
            continue
        for line in text.split("\n"):
            if "25" in line:
                parts = line.split()
                for p in parts:
                    if p.startswith("25") and len(p) >= 10:
                        cotas.append({"inscricao": p, "cota": "COTA"})

cotas = pd.DataFrame(cotas).drop_duplicates("inscricao")

df = df.merge(cotas, on="inscricao", how="left")
df["cota"] = df["cota"].fillna("SEM COTA")
df["psicotecnico"] = df["inscricao"].apply(lambda x: "APTO" if x in psico_aptos else "NÃO APTO")

df["status_final"] = df.apply(
    lambda x: "PASSOU EM TUDO"
    if x["situacao_prova"] == "APROVADO" and x["psicotecnico"] == "APTO"
    else "NÃO PASSOU",
    axis=1
)


df = df.sort_values(by="nota_total", ascending=False).reset_index(drop=True)
df["rank_geral_maringa"] = df.index + 1



aptos = df[df["status_final"] == "PASSOU EM TUDO"].copy()
aptos = aptos.sort_values(by="nota_total", ascending=False).reset_index(drop=True)
aptos["rank_aptos_maringa"] = aptos.index + 1

aptos["rank_cota_maringa"] = (
    aptos.groupby("cota")["nota_total"]
    .rank(method="dense", ascending=False)
    .astype(int)
)


df["nome_normalizado"] = df["nome"].apply(normalize)

if BUSCA.isdigit():
    pessoa = df[df["inscricao"] == BUSCA]
else:
    pessoa = df[df["nome_normalizado"].str.contains(norm_busca, case=False, regex=False)]

if pessoa.empty:
    print("\nCandidato NÃO encontrado em Maringá.")
    quit()

p = pessoa.iloc[0]

print("\n===== RANK DO CANDIDATO (MARINGÁ) =====")
print("Inscrição:", p["inscricao"])
print("Nome:", p["nome"])
print("Nota:", p["nota_total"])
print("Ranking Geral Maringá:", int(p["rank_geral_maringa"]))
print("Situação Prova:", p["situacao_prova"])
print("Psicotécnico:", p["psicotecnico"])
print("Status Final:", p["status_final"])
print("Cota:", p["cota"])

if p["status_final"] == "PASSOU EM TUDO":
    info = aptos[aptos["inscricao"] == p["inscricao"]]
    if not info.empty:
        pr = info.iloc[0]
        print("Ranking entre Aptos Maringá:", int(pr["rank_aptos_maringa"]))
        if pr["cota"] != "SEM COTA":
            print("Ranking dentro da Cota:", int(pr["rank_cota_maringa"]))

import pdfplumber
import pandas as pd
import re
import unicodedata

PDF_PROVA = "arquivo_prova.pdf"
PDF_PSICO = "dbb35138-a62c-45e9-9b89-890b96258841.pdf"
PDF_COTAS = "cotas.pdf"


BUSCA = " 2503008621"



def normalize(s):
    if not isinstance(s, str):
        return s
    return ''.join(c for c in unicodedata.normalize('NFD', s)
                   if unicodedata.category(c) != 'Mn').upper().strip()

norm_busca = normalize(BUSCA)


psico_aptos = set()
with pdfplumber.open(PDF_PSICO) as pdf:
    for page in pdf.pages:
        text = page.extract_text()
        if not text:
            continue
        for line in text.split("\n"):
            parts = line.split()
            if len(parts) >= 3 and parts[-1] == "APTO":
                psico_aptos.add(parts[0])


candidatos = []
padrao = re.compile(
    r"(25\d{8})\s+(.+?)\s+\d+,\d+\s+\d+,\d+\s+(\d+,\d+)\s+(SIM|---)\s+(\d+º)\s+(APROVADO|ELIMINADO)"
)

with pdfplumber.open(PDF_PROVA) as pdf:
    capturar = False
    for page in pdf.pages:
        text = page.extract_text()
        if not text:
            continue

        if "3ª REGIÃO/MARINGÁ" in text.upper():
            capturar = True

        if capturar:
            for m in padrao.finditer(text):
                candidatos.append({
                    "inscricao": m.group(1),
                    "nome": m.group(2).strip(),
                    "nota_total": float(m.group(3).replace(",", ".")),
                    "situacao_prova": m.group(6)
                })

        if "4ª REGIÃO" in text.upper():
            break

df = pd.DataFrame(candidatos)

if df.empty:
    print("Nenhum candidato encontrado em Maringá.")
    quit()


cotas = []
with pdfplumber.open(PDF_COTAS) as pdf:
    for page in pdf.pages:
        text = page.extract_text()
        if not text:
            continue
        for line in text.split("\n"):
            if "25" in line:
                parts = line.split()
                for p in parts:
                    if p.startswith("25") and len(p) >= 10:
                        cotas.append({"inscricao": p, "cota": "COTA"})

cotas = pd.DataFrame(cotas).drop_duplicates("inscricao")

df = df.merge(cotas, on="inscricao", how="left")
df["cota"] = df["cota"].fillna("SEM COTA")
df["psicotecnico"] = df["inscricao"].apply(lambda x: "APTO" if x in psico_aptos else "NÃO APTO")

df["status_final"] = df.apply(
    lambda x: "PASSOU EM TUDO"
    if x["situacao_prova"] == "APROVADO" and x["psicotecnico"] == "APTO"
    else "NÃO PASSOU",
    axis=1
)


df = df.sort_values(by="nota_total", ascending=False).reset_index(drop=True)
df["rank_geral_maringa"] = df.index + 1



aptos = df[df["status_final"] == "PASSOU EM TUDO"].copy()
aptos = aptos.sort_values(by="nota_total", ascending=False).reset_index(drop=True)
aptos["rank_aptos_maringa"] = aptos.index + 1

aptos["rank_cota_maringa"] = (
    aptos.groupby("cota")["nota_total"]
    .rank(method="dense", ascending=False)
    .astype(int)
)

